from bs4 import BeautifulSoup
import requests



start_url = 'http://cd.58.com/sale.shtml?utm_source=market&spm=b-31580022738699-me-f-824.bdpz_biaoti&PGTID=0d100000-0006-69e9-378b-9c20e162f1e3&ClickID=2'

def get_channel_urls(url):
    web_data = requests.get(url)
    soup = BeautifulSoup(web_data.text,'lxml')
    links = soup.select('li span a')
    for link in links:
        if '58' not in str(link.get('href')):
            link_items = 'http://cd.58.com'+str(link.get('href'))
            print(link_items)

channel_urls = """http://cd.58.com/shouji/
http://cd.58.com/shoujihao/
http://cd.58.com/iphonesj/
http://cd.58.com/sanxing/
http://cd.58.com/nuojiya/
http://cd.58.com/htc/
http://cd.58.com/xiaomi/
http://cd.58.com/ailixin/
http://cd.58.com/zhongxingshouji/
http://cd.58.com/lgsj/
http://cd.58.com/kupaisj/
http://cd.58.com/huaweisj/
http://cd.58.com/lianxiang/
http://cd.58.com/motuoluola/
http://cd.58.com/heimei/
http://cd.58.com/jinlisj/
http://cd.58.com/meizu/
http://cd.58.com/shoujipeijian/
http://cd.58.com/chonzhika/
http://cd.58.com/shangwangshebei/
http://cd.58.com/shoujiyewu/
http://cd.58.com/xiaolingtong/
http://cd.58.com/danche/
http://cd.58.com/zixingche/
http://cd.58.com/wanliang/
http://cd.58.com/tabanmotuoche/
http://cd.58.com/qishiche/
http://cd.58.com/dapailiang/
http://cd.58.com/yueyemotuoche/
http://cd.58.com/yamaha/
http://cd.58.com/bentianmoto/
http://cd.58.com/jialing/
http://cd.58.com/lingmumoto/
http://cd.58.com/haojue/
http://cd.58.com/qingqi/
http://cd.58.com/zongshen/
http://cd.58.com/putongzixingche/
http://cd.58.com/zhediezixingche/
http://cd.58.com/minizixingche/
http://cd.58.com/gongluzixingche/
http://cd.58.com/changdizixingche/
http://cd.58.com/shandizixingche/
http://cd.58.com/jieante/
http://cd.58.com/meilida/
http://cd.58.com/yongjiu/
http://cd.58.com/fenghuangzxc/
http://cd.58.com/feige/
http://cd.58.com/jiema/
http://cd.58.com/diandongzixingche/
http://cd.58.com/diandongmotuoche/
http://cd.58.com/zhediediandongche/
http://cd.58.com/minidiandongche/
http://cd.58.com/zhudongche/
http://cd.58.com/jieanteddc/
http://cd.58.com/aima/
http://cd.58.com/xiaoniao/
http://cd.58.com/qingqiddc/
http://cd.58.com/lvyuanddc/
http://cd.58.com/xinri/
http://cd.58.com/jiaotasanlunche/
http://cd.58.com/diandongsanlunche/
http://cd.58.com/zhulisanlunche/
http://cd.58.com/zixingchepeijian/
http://cd.58.com/diandongchekongpeijian/
http://cd.58.com/diandongchedianchi/
http://cd.58.com/xiuchegongju/
http://cd.58.com/qixingzhuangbei/
http://cd.58.com/diannao/
http://cd.58.com/shuma/
http://cd.58.com/taishiji/
http://cd.58.com/fuwuqi/
http://cd.58.com/ibm/
http://cd.58.com/lenovo/
http://cd.58.com/apple/
http://cd.58.com/dell/
http://cd.58.com/asus/
http://cd.58.com/compaq/
http://cd.58.com/sony/
http://cd.58.com/samsung/
http://cd.58.com/pbdnipad/
http://cd.58.com/pbdnsanxing/
http://cd.58.com/pbdnlianxiang/
http://cd.58.com/pbdnaiguozhe/
http://cd.58.com/wangka/
http://cd.58.com/xianshiqi/
http://cd.58.com/cpu/
http://cd.58.com/xianka/
http://cd.58.com/zhuban/
http://cd.58.com/yingpan/
http://cd.58.com/ydyingpan/
http://cd.58.com/zhoubianshebei/pve_5620_398628/
http://cd.58.com/bujianduandianyuan/
http://cd.58.com/shubiao/
http://cd.58.com/shexiangtou/
http://cd.58.com/usb/
http://cd.58.com/smqita/pve_5623_398637/
http://cd.58.com/smqita/pve_5623_398636/
http://cd.58.com/smqita/
http://cd.58.com/danfanxiangji/
http://cd.58.com/kapianxiangji/
http://cd.58.com/weidanxiangji/
http://cd.58.com/jingtou/
http://cd.58.com/xiangjipeijian/
http://cd.58.com/qitaxiangji/
http://cd.58.com/ipod/
http://cd.58.com/mpsantouch/
http://cd.58.com/mpsannano/
http://cd.58.com/mpsan/
http://cd.58.com/mpsi/
http://cd.58.com/psp/
http://cd.58.com/yxjpsv/
http://cd.58.com/yxjnds/
http://cd.58.com/yxjxbox/
http://cd.58.com/yxjpssan/
http://cd.58.com/yxjpser/
http://cd.58.com/yxjwii/
http://cd.58.com/jiadian/
http://cd.58.com/ershoujiaju/
http://cd.58.com/yingyinjiadian/
http://cd.58.com/shenghuojiadian/
http://cd.58.com/chuweijiadian/
http://cd.58.com/jiadianpeijian/
http://cd.58.com/yjcaidian/
http://cd.58.com/gqcaidian/
http://cd.58.com/dlzcaidian/
http://cd.58.com/biguakt/
http://cd.58.com/guishikt/
http://cd.58.com/zhongyangkt/
http://cd.58.com/quanzidongxiyiji/
http://cd.58.com/guntongxiyiji/
http://cd.58.com/shuanggangxiyiji/
http://cd.58.com/minixiyiji/
http://cd.58.com/shuangkaimenbx/
http://cd.58.com/duikaimenbx/
http://cd.58.com/minibx/
http://cd.58.com/lishibg/
http://cd.58.com/wohibg/
http://cd.58.com/zhanshibg/
http://cd.58.com/danrenchuang/
http://cd.58.com/shuanrenchuang/
http://cd.58.com/chuangcengchuang/
http://cd.58.com/zhediechuang/
http://cd.58.com/tongchuang/
http://cd.58.com/chuangdian/
http://cd.58.com/guizi/
http://cd.58.com/zhuolei/
http://cd.58.com/zuoju/
http://cd.58.com/jiajushafa/
http://cd.58.com/chaji/
http://cd.58.com/jujia/
http://cd.58.com/bangong/
http://cd.58.com/shebei.shtml
http://cd.58.com/saomiaoyi/
http://cd.58.com/yitiji/
http://cd.58.com/chuanzhenji/
http://cd.58.com/touyingji/
http://cd.58.com/fuyinji/
http://cd.58.com/dayinji/
http://cd.58.com/tanfen/
http://cd.58.com/mohemoshui/
http://cd.58.com/wenjiangui/
http://cd.58.com/huiyizhuo/
http://cd.58.com/baoxiangui/
http://cd.58.com/bangongzhuoyi/
http://cd.58.com/bangongyi/
http://cd.58.com/bangongjiaju/pve_5733_398638/
http://cd.58.com/bangongjiaju/pve_5733_398639/
http://cd.58.com/huagong/
http://cd.58.com/fangzhi/
http://cd.58.com/fyinshua/
http://cd.58.com/gongcheng/
http://cd.58.com/zaozhi/
http://cd.58.com/kuangye/
http://cd.58.com/mugongshebei/
http://cd.58.com/diandongji/
http://cd.58.com/nongye/
http://cd.58.com/yingyou/
http://cd.58.com/fushi/
http://cd.58.com/muyingzaojiao/
http://cd.58.com/ertongyongpin/
http://cd.58.com/zhiniaoku/
http://cd.58.com/yongpinlalaku/
http://cd.58.com/yongpinbeidai/
http://cd.58.com/yongpinxuebudai/
http://cd.58.com/yongpinyouxidai/
http://cd.58.com/yongpinjianshenjia/
http://cd.58.com/yongpinshuidai/
http://cd.58.com/naifen/
http://cd.58.com/weiyangfushi/
http://cd.58.com/weiyangyingyangpin/
http://cd.58.com/weiyangnaiping/
http://cd.58.com/weiyangnaizui/
http://cd.58.com/weiyangxinaiqi/
http://cd.58.com/weiyangnuannaiqi/
http://cd.58.com/yingerchuang/
http://cd.58.com/yingerche/
http://cd.58.com/tongchexuebu/
http://cd.58.com/tongcheyaoyi/
http://cd.58.com/tongzuoyi/
http://cd.58.com/tongcanyi/
http://cd.58.com/tongniuche/
http://cd.58.com/tongzixingche/
http://cd.58.com/tongsanlunche/
http://cd.58.com/yongpintaixin/
http://cd.58.com/fangfusefu/
http://cd.58.com/mmfuzhuang/
http://cd.58.com/yongpinshoufu/
http://cd.58.com/yongpinyunfuzhen/
http://cd.58.com/fushipeijian/
http://cd.58.com/fuzhuangshoushi/
http://cd.58.com/fuzhuangshoubiao/
http://cd.58.com/fuzhuangtxue/
http://cd.58.com/fuzhuangchenshan/
http://cd.58.com/fuzhuangwaitao/
http://cd.58.com/fuzhuangkuzi/
http://cd.58.com/qunzifs/
http://cd.58.com/fuzhuangxizhuang/
http://cd.58.com/tongzhuang/
http://cd.58.com/xiuxianxie/
http://cd.58.com/yundongxie/
http://cd.58.com/fanbuxie/
http://cd.58.com/gaogenxie/
http://cd.58.com/xiebanxi/
http://cd.58.com/pixie/
http://cd.58.com/xiangbaodanjian/
http://cd.58.com/xiangbaoshuangjian/
http://cd.58.com/xiangbaoshubao/
http://cd.58.com/xiangbaoqianbao/
http://cd.58.com/xiangbaolagan/
http://cd.58.com/xiangbaodiannao/
http://cd.58.com/meirong/
http://cd.58.com/yishu/
http://cd.58.com/meirongyongpin/
http://cd.58.com/hufu/
http://cd.58.com/meirongmeiti/
http://cd.58.com/caizhuang/
http://cd.58.com/baojianshipin/
http://cd.58.com/meifa/
http://cd.58.com/xiangshuimr/
http://cd.58.com/gudongguwan/
http://cd.58.com/mingxingwupin/
http://cd.58.com/shufa/
http://cd.58.com/shanshuihua/
http://cd.58.com/renwuhua/
http://cd.58.com/huaniaohua/
http://cd.58.com/zhuangshihua/
http://cd.58.com/guijinshu/
http://cd.58.com/zhubaoshshi/
http://cd.58.com/fangjinshshi/
http://cd.58.com/zhubaoshipin/pve_5731_398646/
http://cd.58.com/zhubaoshipin/pve_5731_398647/
http://cd.58.com/youpiaoyoupin/
http://cd.58.com/fanggujiaju/
http://cd.58.com/aoyunjinianbi/
http://cd.58.com/sbjinianpin/
http://cd.58.com/tushu/
http://cd.58.com/wenti/
http://cd.58.com/cddvd/
http://cd.58.com/yingpandianshiju/
http://cd.58.com/ruanjiants/
http://cd.58.com/jishulei/
http://cd.58.com/gongjushu/
http://cd.58.com/kaoshi/
http://cd.58.com/shenghuolei/
http://cd.58.com/xiaoshuo/
http://cd.58.com/youyongwt/
http://cd.58.com/yujiawt/
http://cd.58.com/diaoyuyongju/
http://cd.58.com/qipai/
http://cd.58.com/yundongfushi/pve_5728_398644/
http://cd.58.com/yundongfushi/pve_5728_398648/
http://cd.58.com/tabuji/
http://cd.58.com/peobuji/
http://cd.58.com/anmoyi/
http://cd.58.com/liubinghuaban/
http://cd.58.com/jianshenche/
http://cd.58.com/xueshwenju/
http://cd.58.com/jiaoxueyj/
http://cd.58.com/taiqiuzhuo/
http://cd.58.com/wangqiuyongpin/
http://cd.58.com/zuqiuwt/
http://cd.58.com/pingpangqiuwt/
http://cd.58.com/yumaoqiuwt/
http://cd.58.com/lanqiutw/
http://cd.58.com/jita/
http://cd.58.com/gangqin/
http://cd.58.com/dianziqin/
http://cd.58.com/shoufengqing/
http://cd.58.com/erhuwt/
http://cd.58.com/chengren/
http://cd.58.comNone
http://cd.58.com/yintundaomo/
http://cd.58.com/xingwanou/
http://cd.58.com/jiandanbianxie/
http://cd.58.com/nanyongchuandai/
http://cd.58.com/fangzhenrufang/
http://cd.58.com/zhendongbang/
http://cd.58.com/yindiciji/
http://cd.58.com/gdianhouting/
http://cd.58.com/tiaodan/
http://cd.58.com/fengrutiaodou/
http://cd.58.com/jiqingyongju/
http://cd.58.com/qingqutiaosao/
http://cd.58.com/lingleiwanju/
http://cd.58.com/yanshitaohuan/
http://cd.58.com/tiaoqingxiangshui/
http://cd.58.com/zhifuyouhuo/
http://cd.58.com/dingziku/
http://cd.58.com/siwameitui/
http://cd.58.com/nanshineiyi/
http://cd.58.com/runhuaji/
http://cd.58.com/aqyp/
http://cd.58.com/anquantao/
http://cd.58.com/qitachengren/
http://cd.58.com/xiaoyuan/pve_5536_1/
http://cd.58.com/xiaoyuan/pve_5536_2/
http://cd.58.com/xiaoyuan/pve_5536_3/
http://cd.58.com/xiaoyuan/pve_5536_4/
http://cd.58.com/xiaoyuan/pve_5536_5/
http://cd.58.com/esqgjiaju/
http://cd.58.com/esqgfuzhuang/
http://cd.58.com/esqgtushu/
http://cd.58.com/ershouqiugou/
http://cd.58.com/wangyou/
http://cd.58.com/huanwu/
http://cd.58.com/lipin/
http://cd.58.com/wuyuanwupin/
http://cd.58.com/fuwujy/
http://cd.58.com/canjirenyongpin/
http://cd.58.com/weixing/
http://cd.58.com/qitatiaozao/
"""
channel_urls_haoma = """
http://cd.58.com/quanqiutong/
http://cd.58.com/shoujihao/?key=%E5%8A%A8%E6%84%9F%E5%9C%B0%E5%B8%A6
http://cd.58.com/shoujihao/?key=%E7%A5%9E%E5%B7%9E%E8%A1%8C
http://cd.58.com/ruyitong/
http://cd.58.com/cdma/
http://cd.58.com/tietong/
"""